/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class GameHUDUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameHUD");
        }
    }
    REG("ui.GameHUDUI",GameHUDUI);
    export class HomeHUDUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("HomeHUD");
        }
    }
    REG("ui.HomeHUDUI",HomeHUDUI);
    export class LoadUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Load");
        }
    }
    REG("ui.LoadUI",LoadUI);
}