/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { HomeHUD } from "./game_ui/home_hud"
import { Load } from "./load"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Load.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game_ui/home_hud.ts",HomeHUD);
        reg("load.ts",Load);
    }
}
GameConfig.init();